// <auto-generated />
using ASPNET_Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPNETCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240528151708_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPNET_Core.Models.Kitaplar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("BasimYili")
                        .HasColumnType("int");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurId")
                        .HasColumnType("int");

                    b.Property<string>("YazarAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("TurId");

                    b.ToTable("Kitaplars");
                });

            modelBuilder.Entity("ASPNET_Core.Models.Turler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("KitapTur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RafNo")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Turlers");
                });

            modelBuilder.Entity("ASPNET_Core.Models.Kitaplar", b =>
                {
                    b.HasOne("ASPNET_Core.Models.Turler", "Turler")
                        .WithMany("Kitaplars")
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turler");
                });

            modelBuilder.Entity("ASPNET_Core.Models.Turler", b =>
                {
                    b.Navigation("Kitaplars");
                });
#pragma warning restore 612, 618
        }
    }
}
